### ISSUE TITLE
Error name 'pipe' is not defined

### ISSUE THREAD

**Issue by zboing** [nitrosocke/diffusers-webui#1]
After pressing the button "Generate" the following error is shown: name 'pipe' is not defined

**Comment by nitrosocke** [comment]
Can you send the Line of code which this error originates from?
Did you enable the xformers in the script?

**Comment by zboing** [comment]
with pipe.enable_xformers_memory_efficient_attention() enabled

Traceback (most recent call last):
  File "C:\Users\damia\Desktop\diffusers-webui-main\launch.py", line 73, in <module>
    start()
  File "C:\Users\damia\Desktop\diffusers-webui-main\launch.py", line 67, in start
    import app
  File "C:\Users\damia\Desktop\diffusers-webui-main\app.py", line 67, in <module>
    pipe.enable_xformers_memory_efficient_attention()
NameError: name 'pipe' is not defined
Press any key to continue . . .

when it's disabled I receive the error in the web application without saying the specific line

**Comment by nitrosocke** [comment]
Thank you for your error report!
I found the error in the app and updated the script. please make a `git pull` or update the "app.py" script manually by redownloading it.

**Comment by zboing** [comment]
Unfortunately the error still appears in the web gui
